package config

type Language struct {
	Code         string            `json:"code"`
	Name         string            `json:"name"`
	NativeName   string            `json:"native_name"`
	Translations map[string]string `json:"translations"`
}

func Languages() []Language {
	return []Language{
		{
			Code:       "uk",
			Name:       "Ukrainian",
			NativeName: "Українська",
			Translations: map[string]string{
				"app.by":                     "від",
				"nav.download":               "Завантаження",
				"nav.settings":               "Налаштування",
				"nav.logs":                   "Логи",
				"mode.movie":                 "Фільм",
				"mode.series":                "Серіал",
				"source.label":               "Джерело",
				"source.list":                "Файл списку",
				"source.direct":              "Прямі посилання",
				"field.url":                  "URL",
				"field.list":                 "LIST",
				"field.title":                "НАЗВА",
				"field.series":               "СЕРІАЛ",
				"field.season":               "СЕЗОН",
				"field.links":                "ПОСИЛАННЯ",
				"field.save":                 "SAVE",
				"button.download":            "ЗАВАНТАЖИТИ",
				"button.pause":               "ПАУЗА",
				"button.resume":              "ПРОДОВЖИТИ",
				"button.reload":              "ОНОВИТИ",
				"button.save":                "ЗБЕРЕГТИ",
				"button.clear":               "ОЧИСТИТИ",
				"button.file":                "ФАЙЛ",
				"stats.download":             "Завантаження",
				"stats.waiting":              "Очікування",
				"stats.segments":             "Сегменти",
				"stats.fragments":            "HLS фрагменти",
				"stats.speed":                "Швидкість",
				"settings.title":             "Налаштування",
				"settings.config_path":       "Шлях до конфіга",
				"settings.paths":             "Шляхи",
				"settings.ytdlp_ffmpeg":      "YTDLP / FFmpeg",
				"settings.ytdlp":             "yt-dlp",
				"settings.ffmpeg":            "ffmpeg",
				"settings.movies":            "Фільми",
				"settings.series":            "Серіали",
				"settings.links":             "Посилання",
				"settings.log_file":          "Файл логів",
				"settings.max_parallel":      "Максимум паралельно",
				"settings.retries":           "Повторні спроби",
				"settings.retry_delay":       "Затримка повтору",
				"settings.fragments":         "Фрагменти",
				"settings.ytdlp_retries":     "yt-dlp спроби",
				"settings.fragment_retries":  "Спроби фрагмента",
				"settings.container":         "Контейнер",
				"settings.browser_cookies":   "Cookies браузера",
				"settings.safe_mode":         "Безпечний режим",
				"settings.continue":          "Продовження",
				"settings.hls_mpegts":        "HLS MPEG-TS",
				"settings.language":          "Мова",
				"logs.title":                 "Логи",
				"logs.path":                  "Шлях до логу",
				"logs.empty":                 "Логи порожні.",
				"status.ready":               "Встав посилання і почни завантаження.",
				"status.movie_ready":         "Режим фільму готовий.",
				"status.series_ready":        "Режим серіалу готовий.",
				"status.config_loaded":       "Конфіг завантажено.",
				"status.config_saved":        "Конфіг збережено.",
				"status.config_reloaded":     "Конфіг оновлено.",
				"status.log_loaded":          "Лог завантажено.",
				"status.no_logs":             "Записів у логах ще немає.",
				"status.log_cleared":         "Лог очищено.",
				"status.log_opened":          "Файл логу відкрито в Explorer.",
				"status.download_starting":   "Починаю завантаження...",
				"status.preparing":           "Підготовка",
				"status.complete":            "Готово",
				"status.in_progress":         "В процесі",
				"status.failed":              "Помилка",
				"status.paused":              "Завантаження на паузі.",
				"status.resumed":             "Завантаження продовжено.",
				"status.manifest_wait":       "Очікування маніфесту",
				"validation.url":             "Спочатку встав URL відео.",
				"validation.list":            "Спочатку вкажи файл списку.",
				"validation.links":           "Додай хоча б одне посилання.",
				"validation.season":          "Спочатку вкажи номер сезону.",
				"placeholder.url":            "http://www.example.ua",
				"placeholder.title":          "MAD MAX",
				"placeholder.series":         "Назва серіалу",
				"placeholder.list":           "url_list.ini",
				"placeholder.links":          "Одне посилання на рядок",
				"placeholder.default_folder": "Папка за замовчуванням",
			},
		},
		{
			Code:       "en",
			Name:       "English",
			NativeName: "English",
			Translations: map[string]string{
				"app.by":                     "by",
				"nav.download":               "Download",
				"nav.settings":               "Settings",
				"nav.logs":                   "Logs",
				"mode.movie":                 "Movie",
				"mode.series":                "Series",
				"source.label":               "Input source",
				"source.list":                "List file",
				"source.direct":              "Direct links",
				"field.url":                  "URL",
				"field.list":                 "LIST",
				"field.title":                "TITLE",
				"field.series":               "SERIES",
				"field.season":               "SEASON",
				"field.links":                "LINKS",
				"field.save":                 "SAVE",
				"button.download":            "DOWNLOAD",
				"button.pause":               "PAUSE",
				"button.resume":              "RESUME",
				"button.reload":              "RELOAD",
				"button.save":                "SAVE",
				"button.clear":               "CLEAR",
				"button.file":                "FILE",
				"stats.download":             "Download",
				"stats.waiting":              "Waiting",
				"stats.segments":             "Segments",
				"stats.fragments":            "HLS fragments",
				"stats.speed":                "Speed",
				"settings.title":             "Settings",
				"settings.config_path":       "Config path",
				"settings.paths":             "Paths",
				"settings.ytdlp_ffmpeg":      "YTDLP / FFmpeg",
				"settings.ytdlp":             "yt-dlp",
				"settings.ffmpeg":            "ffmpeg",
				"settings.movies":            "Movies",
				"settings.series":            "Series",
				"settings.links":             "Links",
				"settings.log_file":          "Log file",
				"settings.max_parallel":      "Max parallel",
				"settings.retries":           "Retries",
				"settings.retry_delay":       "Retry delay",
				"settings.fragments":         "Fragments",
				"settings.ytdlp_retries":     "yt-dlp retries",
				"settings.fragment_retries":  "Fragment retries",
				"settings.container":         "Container",
				"settings.browser_cookies":   "Browser cookies",
				"settings.safe_mode":         "Safe mode",
				"settings.continue":          "Continue",
				"settings.hls_mpegts":        "HLS MPEG-TS",
				"settings.language":          "Language",
				"logs.title":                 "Logs",
				"logs.path":                  "Log path",
				"logs.empty":                 "Logs are empty.",
				"status.ready":               "Paste the URL and start the download.",
				"status.movie_ready":         "Movie mode ready.",
				"status.series_ready":        "Series mode ready.",
				"status.config_loaded":       "Config loaded.",
				"status.config_saved":        "Config saved.",
				"status.config_reloaded":     "Config reloaded.",
				"status.log_loaded":          "Log loaded.",
				"status.no_logs":             "No log entries yet.",
				"status.log_cleared":         "Log cleared.",
				"status.log_opened":          "Log file opened in Explorer.",
				"status.download_starting":   "Starting download...",
				"status.preparing":           "Preparing",
				"status.complete":            "Complete",
				"status.in_progress":         "In progress",
				"status.failed":              "Failed",
				"status.paused":              "Download paused.",
				"status.resumed":             "Download resumed.",
				"status.manifest_wait":       "Waiting for manifest",
				"validation.url":             "Paste a video URL first.",
				"validation.list":            "Paste a list file name first.",
				"validation.links":           "Add at least one URL.",
				"validation.season":          "Set season number first.",
				"placeholder.url":            "http://www.example.ua",
				"placeholder.title":          "MAD MAX",
				"placeholder.series":         "Series Name",
				"placeholder.list":           "url_list.ini",
				"placeholder.links":          "One URL per line",
				"placeholder.default_folder": "Default folder",
			},
		},
	}
}

func SupportedLanguage(code string) bool {
	code = normalizeLanguage(code)
	for _, language := range Languages() {
		if language.Code == code {
			return true
		}
	}
	return false
}

func normalizeLanguage(code string) string {
	switch code {
	case "ua":
		return "uk"
	default:
		return code
	}
}
