// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory(arg1) {
  return window['go']['main']['App']['BrowseDirectory'](arg1);
}

export function BrowseFile(arg1) {
  return window['go']['main']['App']['BrowseFile'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function ClearLog() {
  return window['go']['main']['App']['ClearLog']();
}

export function DownloadMovie(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadMovie'](arg1, arg2, arg3);
}

export function DownloadSeries(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadSeries'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadSeriesLinks(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadSeriesLinks'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogEvent(arg1, arg2) {
  return window['go']['main']['App']['LogEvent'](arg1, arg2);
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function PauseDownload() {
  return window['go']['main']['App']['PauseDownload']();
}

export function ReadLog() {
  return window['go']['main']['App']['ReadLog']();
}

export function ResumeDownload() {
  return window['go']['main']['App']['ResumeDownload']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
