// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function BrowseDirectory(arg1:string):Promise<string>;

export function BrowseFile(arg1:string):Promise<string>;

export function CancelDownload():Promise<boolean>;

export function ClearLog():Promise<void>;

export function DownloadMovie(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadSeries(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DownloadSeriesLinks(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetConfig():Promise<config.Config>;

export function GetConfigPath():Promise<string>;

export function GetLanguages():Promise<Array<config.Language>>;

export function Greet(arg1:string):Promise<string>;

export function LogEvent(arg1:string,arg2:string):Promise<void>;

export function OpenLogFile():Promise<void>;

export function PauseDownload():Promise<void>;

export function ReadLog():Promise<string>;

export function ResumeDownload():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;
